In [1]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


학습 데이터를 만든다.

In [2]:
# xData => [공부 시간, 과외 시간]
temp = [[2, 3], [4, 3], [6, 4], [8, 6], [10, 7], [12, 8], [14, 9]]
print(temp)
print(type(temp))

xData = np.array(temp)
print(xData)
print(type(xData))

[[2, 3], [4, 3], [6, 4], [8, 6], [10, 7], [12, 8], [14, 9]]
<class 'list'>
[[ 2  3]
 [ 4  3]
 [ 6  4]
 [ 8  6]
 [10  7]
 [12  8]
 [14  9]]
<class 'numpy.ndarray'>


In [3]:
# yData => [합격 여부] => 실제값, 0: 불합격, 1: 합격
temp = [0, 0, 0, 1, 1, 1, 1]
print(temp)
print(type(temp))

yData = np.array(temp)
print(yData)
print(type(yData))
# reshape() 함수는 데이터는 그대로 유지한 채 배열의 형태(차원, 구조)를 변경한다. 1행 7열 넘파이 배열 => 7행 1열 넘파이 배열
yData = np.array(temp).reshape(7, 1)
print(yData)
print(type(yData))

[0, 0, 0, 1, 1, 1, 1]
<class 'list'>
[0 0 0 1 1 1 1]
<class 'numpy.ndarray'>
[[0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]]
<class 'numpy.ndarray'>


xData와 yData를 저장할 placeholder를 만든다.

In [4]:
# placeholder에 넘파이 배열을 대입하는 경우 shape 속성을 이용해 대입되는 넘파이 배열의 차원을 지정해줘야 한다.
# [None, 2] => placeholder에 대입되는 넘파이 배열의 행의 개수는 몇개라도 상관이 없고 열의 개수는 무조건 2개이다.
X = tf.placeholder(dtype=tf.float32, shape=[None, 2]) # xData가 대입될 placeholder
Y = tf.placeholder(dtype=tf.float32, shape=[None, 1]) # yData가 대입될 placeholder

기울기(가중치) a와 y절편(바이어스) b를 임의로 정한다.

In [5]:
a = tf.Variable(tf.random_uniform([2, 1]), dtype=tf.float32) # 난수를 2행 1열로 만든다. => 행렬의 내적을 이용해 처리한다.
b = tf.Variable(tf.random_uniform([1]), dtype=tf.float32)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print('a: {}'.format(sess.run(a)))
print('b: {}'.format(sess.run(b)))
print('a1: {}, a2: {}, b: {}'.format(sess.run(a)[0], sess.run(a)[1], sess.run(b)))

a: [[0.8595178]
 [0.6666113]]
b: [0.3510437]
a1: [0.8595178], a2: [0.6666113], b: [0.3510437]


시그모이드 방정식, 오차 함수, 경사 하강

In [6]:
# sigmoid(): tensorflow에서 시그모이드 방정식을 계산하는 함수
# matmul(): tensorflow에서 행렬의 곱셈을 계산하는 함수
y = tf.sigmoid(tf.matmul(X, a) + b) # 시그모이드 방정식
loss = -tf.reduce_mean(Y * tf.log(y) + (1 - Y) * tf.log(1 - y)) # 오차 함수
gradient_descent = tf.train.GradientDescentOptimizer(0.1).minimize(loss) # 경사 하강

sigmoid() 함수의 실행 결과(y)가 0.5 이상이면 1을 0.5 미만이면 0을 리턴시킨다.

In [7]:
sess = tf.Session()
# cast(캐스팅할 데이터, dtype=캐스팅될 데이터 타입): tensorflow에서 형변환을 하는 함수
# predicted = tf.cast(tf.constant([1.9, 2.1]), dtype=tf.int32)
# print(sess.run(predicted)) # [1 2]

# cast() 함수의 캐스팅할 데이터가 boolean 타입이면 True는 1로 False는 0으로 캐스팅 된다.
predicted = tf.cast(0.4 >= 0.5, dtype=tf.float32)
print(sess.run(predicted))
predicted = tf.cast(0.5 >= 0.5, dtype=tf.float32)
print(sess.run(predicted))

0.0
1.0


sigmoid() 함수를 실행한 예상값을 계산한다.

In [8]:
predicted = tf.cast(y >= 0.5, dtype=tf.float32) # 예측값, sigmoid() 함수를 실행한 결과(y)를 0 또는 1로 변환한다.
# 예측값이 실제값과 일치하는 정도(정확도)를 계산한다.
# equal(): tensorflow에서 인수로 지정된 값이 같으면 True, 다르면 False를 리턴하는 함수
# equal() 함수로 예측값(predicted)과 실제값(Y)이 같은가 비교한 후 True 또는 False 결과를 1 또는 0으로 캐스팅히고 시행된 전체
# 결과의 평균을 계산한다.
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

학습을 시킨다.

In [47]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for i in range(3001):
    # sess.run([기울기, y절편, 오차함수, 경사하강], feed_dict={X: 입력 데이터, Y: 입력 데이터에 따른 실제값})
    # 연산은 하긴 하는데 사용하지 않을 실행 결과를 기억하는 변수는 '_'로 사용한다.
    a_, b_, loss_, _ = sess.run([a, b, loss, gradient_descent], feed_dict={X: xData, Y: yData})
    if i % 300 == 0:
        # Epoch: 학습 횟수, a1: 공부 시간 기울기, a2: 과외 시간 기울기, b: y절편, loss: 오차함수
        # print('Epoch: %4d, a1: %9.5f, a2: %9.5f, b: %9.5f, loss: %9.5f' % (i, a_[0], a_[1], b_, loss_))
        print('Epoch: {0:4d}, a1: {1:9.5f}, a2: {2:9.5f}, b: {3:9.5f}, loss: {4:9.5f}'.format(i, a_[0][0], a_[1][0], 
                            b_[0], loss_))
# ===========================================

print('=' * 80)
# 테스트 데이터를 만든다.
# new_x = np.array([6, 5]) # 테스트 데이터가 1차원 넘파이 배열이기 때문에 행렬의 곱셈 연산이 실행되지 않는다.
# print(new_x)       # [6 5]   => 1차원
# print(new_x.shape) # (2,)    => 1차원
# print(new_x.ndim)  # 1       => 1차원
# reshape() 함수로 테스트 데이터를 1행 2열인 2차원 넘파이 배열로 변환해야 행렬의 곱셈 연산이 제대로 실행된다.
new_x = np.array([6, 5]).reshape(1, 2)
# print(new_x)       # [[6 5]] => 2차원
# print(new_x.shape) # (1, 2)  => 2차원
# print(new_x.ndim)  # 2       => 2차원

# sigmoid() 함수의 연산 결과에 테스트 데이터를 대입해서 연산한다.
result, new_y = sess.run([predicted, y], feed_dict={X: new_x})
# print('공부 시간: {}, 과외 시간: {}'.format(new_x[:, 0][0], new_x[:, 1][0]))
# print('공부 시간: {}, 과외 시간: {}'.format(new_x[0, 0], new_x[0, 1]))
print('공부 시간: %d, 과외 시간: %d' % (new_x[:, 0], new_x[:, 1]))
# print('합격 여부: {0:1.0f}, 합격 확률: {1:6.2f}%'.format(result[0][0], new_y[0][0] * 100))
# print('합격 여부: {0:s}, 합격 확률: {1:6.2f}%'.format('합격' if result[0][0] == 1 else '불합격', new_y[0][0] * 100))
print('합격 여부: %s, 합격 확률: %6.2f%%' % ('합격' if result[0][0] == 1 else '불합격', new_y[0][0] * 100))
print('=' * 80)

# 공부는 1시간도 안하고 과외 수업 0 ~ 10 시간을 받았을 때 합격 여부와 합격 확률
for i in range(11):
    new_x = np.array([0, i]).reshape(1, 2)
    result, new_y = sess.run([predicted, y], feed_dict={X: new_x})
    print('공부 시간: %d, 과외 시간: %2d' % (new_x[:, 0], new_x[:, 1]), end=' ')
    print('합격 여부: %s, 합격 확률: %6.2f%%' % ('  합격' if result[0][0] == 1 else '불합격', new_y[0][0] * 100))

Epoch:    0, a1:   0.47955, a2:   0.02234, b:   0.91733, loss:   1.76440
Epoch:  300, a1:   0.93082, a2:  -0.78180, b:  -2.07075, loss:   0.29012
Epoch:  600, a1:   0.90964, a2:  -0.46687, b:  -3.62133, loss:   0.20529
Epoch:  900, a1:   0.80354, a2:  -0.10744, b:  -4.73709, loss:   0.15879
Epoch: 1200, a1:   0.68707, a2:   0.22354, b:  -5.61450, loss:   0.12890
Epoch: 1500, a1:   0.57806, a2:   0.51575, b:  -6.33851, loss:   0.10812
Epoch: 1800, a1:   0.48066, a2:   0.77154, b:  -6.95506, loss:   0.09291
Epoch: 2100, a1:   0.39494, a2:   0.99592, b:  -7.49203, loss:   0.08135
Epoch: 2400, a1:   0.31973, a2:   1.19393, b:  -7.96771, loss:   0.07230
Epoch: 2700, a1:   0.25355, a2:   1.36996, b:  -8.39469, loss:   0.06503
Epoch: 3000, a1:   0.19504, a2:   1.52765, b:  -8.78208, loss:   0.05908
공부 시간: 6, 과외 시간: 5
합격 여부: 합격, 합격 확률:  50.66%
공부 시간: 0, 과외 시간:  0 합격 여부: 불합격, 합격 확률:   0.02%
공부 시간: 0, 과외 시간:  1 합격 여부: 불합격, 합격 확률:   0.07%
공부 시간: 0, 과외 시간:  2 합격 여부: 불합격, 합격 확률:   0.32%
공부 시간: 0, 과